### ISSUE TITLE
@media syntax seems incorrect

### ISSUE THREAD

**Issue by aarongustafson** [fallaciousreasoning/backbutton-mediaquery#2]
Media queries should have parentheses:

```css
@media (navigation-controls) {
    #back-button {
        display-none;
    }
}
```

This is borne out in the documentation you reference, [for example in update](https://www.w3.org/TR/mediaqueries-4/#descdef-media-update).

**Comment by fallaciousreasoning** [comment]
Good catch! Out of interest, did you want this API for something?

**Comment by aarongustafson** [comment]
Not me in particular, but I was part of the discussion of this feature request.

**Comment by aarongustafson** [comment]
@fallaciousreasoning The example JavaScript code would also need updating, right?

```js
const backButtonQuery = window.matchMedia('(navigation-controls)');
```

Also, just for clarification, right now the media query for navigation controls is allowed to be boolean, but more granular testing should also be possible. Is that correct? So these would also be valid:

```css
@media (navigation-controls: back) {
    #back-button {
        display-none;
    }
}
```

```js
const backButtonQuery = window.matchMedia('(navigation-controls: none)');
```

**Comment by Malvoz** [comment]
> So these would also be valid:
> `@media (navigation-controls: back)`

Yes. I'm still learning to read specs so I'll just post you the info to that conclusion:

In the explainer's "[API Proposal](https://github.com/fallaciousreasoning/backbutton-mediaquery/blob/master/explainer.md#api-proposal)" section:

> A CSS Media query navigation-controls which determines what navigation controls are currently available, with the possible values `'none' | 'back'`, and the possibility of being extended with `'back-and-forward'` in future. However, the API is designed to be used in a [boolean context,](https://www.w3.org/TR/mediaqueries-4/#mq-boolean-context) so all future values should imply the presence of a back button (e.g. we wouldn't add a separate 'forward' value).
> 
> _Note: This value is an enum not a boolean because `<mq-boolean>` is intended for [legacy purposes only](https://www.w3.org/TR/mediaqueries-4/#grid), with the spec noting that "If this feature were being designed today, it would instead use proper named keywords for its values."_

https://www.w3.org/TR/mediaqueries-4/#mq-boolean-context:

> 2.4.2. Evaluating Media Features in a Boolean Context
> 
> While media features normally have a syntax similar to CSS properties, they can also be written more simply as just the feature name, like `(color)`.
> 
> When written like this, the media feature is evaluated in a _boolean context_. If the feature would be true for any value _other than_ the number `0`, a `<dimension>` with the value `0`, or the keyword `none`, the media feature evaluates to `true`. Otherwise, it evaluates to `false`.

So `@media (navigation-controls)` or `@media (navigation-controls: back|back-and-forward)` would all indicate the presence of a back-button.

**Comment by aarongustafson** [comment]
Yep, I just wanted to call it out as this will be important for implementors to keep in mind for parsing and authors to be aware of when building sites.

For further clarity, it might be worth indicating that `@media (navigation-controls: none)` would apply if:

1. the UA understands this media query and
2. it is not presenting any navigation controls.

**Comment by fallaciousreasoning** [comment]
> @fallaciousreasoning The example JavaScript code would also need updating, right?

Whoops, yes :)

> Also, just for clarification, right now the media query for navigation controls is allowed to be boolean, but more granular testing should also be possible. Is that correct?

Yup that's my understanding of it (though I'm pretty far from an expert).

Thanks for your input here :) I'm afraid the feature is pretty far down my priorities list at the moment, so its going to be a while before I can give it the attention it deserves :/

(I've updated the explainer with both of your feedback but speccing/test implementation are a ways off).
